// <auto-generated />
namespace SocialNetwork.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class addlikestoPost : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addlikestoPost));
        
        string IMigrationMetadata.Id
        {
            get { return "201607191405429_add likes to Post"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
